# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ifPrimo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelIMAGEM = QtWidgets.QLabel(self.centralwidget)
        self.labelIMAGEM.setGeometry(QtCore.QRect(-70, -10, 1101, 631))
        self.labelIMAGEM.setText("")
        self.labelIMAGEM.setPixmap(QtGui.QPixmap("../../../../Downloads/GettyImages-478186903-corr.webp"))
        self.labelIMAGEM.setScaledContents(True)
        self.labelIMAGEM.setObjectName("labelIMAGEM")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(380, 30, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(300, 30, 311, 101))
        self.widget.setStyleSheet("background-color:rgb(255, 170, 255);color: white")
        self.widget.setObjectName("widget")
        self.inputLine = QtWidgets.QLineEdit(self.widget)
        self.inputLine.setGeometry(QtCore.QRect(0, 70, 311, 31))
        self.inputLine.setObjectName("inputLine")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.inputLine.raise_()
        self.confirmBtn = QtWidgets.QPushButton(self.centralwidget)
        self.confirmBtn.setGeometry(QtCore.QRect(360, 160, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.confirmBtn.setFont(font)
        self.confirmBtn.setStyleSheet("background-color: rgb(255, 255, 255); border-radius: 20px; border: 2px solid black;")
        self.confirmBtn.setObjectName("confirmBtn")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(420, 260, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.result.setFont(font)
        self.result.setStyleSheet("border: 1px solid black; background-color: white;")
        self.result.setText("")
        self.result.setObjectName("result")
        self.frame.raise_()
        self.labelIMAGEM.raise_()
        self.widget.raise_()
        self.confirmBtn.raise_()
        self.result.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 949, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Digite o número"))
        self.confirmBtn.setText(_translate("MainWindow", "É primo?"))
